# Generated by Django 3.1.3 on 2020-11-25 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('setor', models.CharField(choices=[('alimentos', 'Alimentos'), ('alocacao_carros', 'Alocação de carros e Gestão de frotas'), ('agricultura', 'Agricultura'), ('bens_industriais', 'Bens industriais'), ('contrucao_civil', 'Construção e Engenharia'), ('celulose', 'Celulose'), ('educacional', 'Educacional'), ('exploracao_imoveis', 'Exploração de imóveis e Shoppings'), ('energia_eletrica', 'Energia elétrica'), ('financeiro', 'Financeiro'), ('farmacia', 'Farmácia'), ('holding', 'Holding'), ('mineiracao', 'Mineiração'), ('metalurgia', 'Metalurgia'), ('medicina_diagnostica', 'Medicina Diagnóstica'), ('petroleo', 'Petróleo, Gás e Combustível'), ('quimica', 'Química e Petroquímica'), ('saneamento', 'Saneamento'), ('seguros', 'Seguros'), ('saude', 'Saúde'), ('transporte_logistica', 'Transporte e Logística'), ('turismo', 'Turismo'), ('telecomunicacoes', 'Telecomunicações'), ('tecnologia', 'Tecnologia'), ('vestuario', 'Vestuário'), ('varejo', 'Varejo e Consumo'), ('outros', 'Outros')], max_length=200, verbose_name='Setor')),
                ('flag_habilitado_operar', models.BooleanField(default=True, verbose_name='Habilitado para operar?')),
                ('dias_calculo', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Dias para calculo')),
                ('porcentagem_desconto', models.IntegerField(default=85, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(70)], verbose_name='Porcentagem para desconto')),
                ('desconto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto calculado')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor investido')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=200, verbose_name='Conta')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia do vencimento')),
            ],
            options={
                'verbose_name': 'Conta',
            },
        ),
        migrations.CreateModel(
            name='DayTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(verbose_name='Data da movimentação')),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('corretora', models.CharField(choices=[('', '--------'), ('inter', 'Banco Inter'), ('clear', 'Clear'), ('terra', 'Terra')], max_length=200, verbose_name='Corretora')),
                ('tipo_bolsa', models.CharField(choices=[('', '--------'), ('bmef', 'BM&F'), ('bovespa', 'Bovespa')], max_length=20)),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor bruto')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxas')),
                ('emulentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emulentos')),
                ('corretagem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Emulentos')),
                ('irrf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IR retido na fonte')),
            ],
            options={
                'verbose_name': 'Day Trade',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_receita', models.CharField(choices=[('picpay', 'PicPay'), ('carpool', 'Carpool')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_receita', models.DateField(verbose_name='Data da receita')),
            ],
        ),
        migrations.CreateModel(
            name='SwingTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('data_acao', models.DateTimeField(verbose_name='Data da Swing Trade')),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='core.swingtrade')),
                ('vendido', models.BooleanField(blank=True, default=False, null=True)),
                ('tipo_movimentacao', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=10)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ativos')),
            ],
            options={
                'verbose_name': 'Compra e Venda',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do pagamento')),
                ('mes_vigente', models.IntegerField(verbose_name='Mês vigente do pagamento')),
                ('ano_vigente', models.IntegerField(verbose_name='Ano vigente do pagamento')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
                ('user_own', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('valor_abertura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor abertura')),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor fechamento')),
                ('valor_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor máxima')),
                ('valor_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínima')),
                ('diff_minima_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença entre a mínina e fechamento')),
                ('diff_minima_fechamento_dia_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença entre a mínina do dia e fechamento do dia anterior')),
                ('variacao_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Variação do dia')),
                ('diferenca_variacao_com_ibov', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença de variação com IBOV')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ativos')),
            ],
            options={
                'verbose_name': 'Histórico do ativo',
            },
        ),
        migrations.AddConstraint(
            model_name='daytrade',
            constraint=models.UniqueConstraint(fields=('data_acao', 'tipo_bolsa', 'corretora'), name='unique_day_trade_dia'),
        ),
        migrations.AddConstraint(
            model_name='historicoativo',
            constraint=models.UniqueConstraint(fields=('ativo', 'data'), name='unique_data_por_ativo'),
        ),
    ]
