# Generated by Django 3.1.3 on 2020-11-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
